# Generated by Django 2.1.7 on 2019-05-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated',
            field=models.CharField(default='unknown', max_length=60),
        ),
    ]
