# Generated by Django 2.1.7 on 2019-05-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0005_auto_20190521_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='days',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sport',
            name='title',
            field=models.TextField(),
        ),
    ]
