# Generated by Django 2.1.7 on 2019-05-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0006_auto_20190521_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='sixthCourse',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='musicLesson',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='sport',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='topPriority',
            field=models.IntegerField(default=-1),
        ),
    ]
